name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Запуск при пуше в main

jobs:
  build:
    runs-on: ubuntu-latest  # Используем последнюю версию Ubuntu

    steps:
      - name: Checkout репозиторий
        uses: actions/checkout@v3

      - name: Установка Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Версия Node.js (проверьте, какая нужна вашему проекту)

      - name: Установка зависимостей
        run: npm install

      - name: Сборка проекта
        run: npm run build  # Убедитесь, что в package.json есть соответствующий скрипт

      - name: Деплой в ветку gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Папка со статическими файлами после сборки
          publish_branch: gh-pages

